apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jobs-collector.fullname" . }}-config
  namespace: {{ include "jobs-collector.namespace" . }}
  labels:
    {{- include "jobs-collector.labels" . | nindent 4 }}
data:
  DB_CONNECTION: {{ .Values.env.DB_CONNECTION | quote }}
  DB_HOST: {{ include "jobs-collector.mysql.fullname" . | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  DB_DATABASE: {{ .Values.mysql.auth.database | quote }}
  API_PORT: {{ .Values.env.API_PORT | quote }}
