{{- if not .Values.mysql.auth.existingSecret }}
{{- $secretName := include "jobs-collector.secretName" . -}}
{{- $existingSecret := lookup "v1" "Secret" (include "jobs-collector.namespace" .) $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "jobs-collector.namespace" . }}
  labels:
    {{- include "jobs-collector.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.mysql.auth.username | b64enc | quote }}
  db-password: {{- if .Values.mysql.auth.password }} {{ .Values.mysql.auth.password | b64enc | quote }}{{- else if and $existingSecret (index $existingSecret.data "db-password") }} {{ index $existingSecret.data "db-password" | quote }}{{- else }} {{ randAlphaNum 32 | b64enc | quote }}{{- end }}
  db-root-password: {{- if .Values.mysql.auth.rootPassword }} {{ .Values.mysql.auth.rootPassword | b64enc | quote }}{{- else if and $existingSecret (index $existingSecret.data "db-root-password") }} {{ index $existingSecret.data "db-root-password" | quote }}{{- else }} {{ randAlphaNum 32 | b64enc | quote }}{{- end }}
{{- end }}
